name: CI & Deploy React Vite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: 🧪 Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build

  deploy:
    name: 🚀 Deploy to Vercel
    needs: test-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Vercel Deploy
        uses: vercel/action@v3
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}        # Configure em Settings > Secrets
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}       # Obtenha em Vercel dashboard
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Obtenha em Vercel dashboard
          vercel-args: '--prod'
          working-directory: .
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
